/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sci_cclj_LuaJITMachine */

#ifndef _Included_com_sci_cclj_LuaJITMachine
#define _Included_com_sci_cclj_LuaJITMachine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sci_cclj_LuaJITMachine
 * Method:    test
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sci_cclj_LuaJITMachine_test
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
